[package]
name = "virust-splicing"
version = "0.1.0"
edition = "2024"
default-run = "virust-splicing"

[dependencies]
bio = "2.2.0"
colored = "3"
serde = "1"
serde_json = "1"
tap = "1"
config = "0.15"
rayon = "1.10"
itertools = "0.14"
csv = "1.3"
rand = "0.9"
rand_chacha = "0.9"
rand_distr = "0.5"
plotters = "0.3"
regex = "1.11"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false

[[bin]]
name = "mockdata"
path = "src/bin/mockdata/main.rs"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[profile.release-with-debug]
inherits = "release"
debug = true